### ISSUE TITLE
Replantamiento del proyecto

### ISSUE THREAD

**Issue by marianoheller** [marianoheller/rageboard#1]
Me parece que quizas se puede replantear el proyecto como "dashboard de enojo" o algo similar.
E incluso, teniendo un backend, se podria tambien incluir la api de azure devops para levantar el numero de bugs por ej (haciendo el codigo bien generico para no mostrar nada q no haya q mostar y utilizando variables de entorno al maximo)
El resultado seguiria siendo el mismo, una medidor con una aguja q mide un numero.

Por otro lado para el clima muchos recomiendan la api de OpenWeatherMap que necesita una cuenta para api key, asique tambien por ese lado vendria bien tener backend que maneje las keys.

**Comment by ivanfranco502** [comment]
Lo que veo es que para incluir interacción con DevOps vamos a tener que generar un PAT y no se si esté bueno. Se puede poner en un archivo de configuración pero me hace ruido integrar con DevOps (poco serio) jaja.

**Comment by marianoheller** [comment]
Claro, tenes razón..
Y con lo otro estás de acuerdo?
Tendriamos backend? Habiamos dicho Node o Python?
Para hacerlo más interesante podemos usar sockets en vez de ajax normales. Eso en Node es bastante simple, python desconozco.

PS: No avisó por mail q respondiste :(

**Comment by ivanfranco502** [comment]
Me gustaría que tuviera back, simplemente porque me siento más cómodo con él jaja. El lenguaje en particular, me da lo mismo.

Tengo un poco de conocimiento de Python pero tirado a data analysis y Node nunca toqué nada. Vamos con el que vos prefieras.

**Comment by marianoheller** [comment]
Hmm 🤔 
Dado que en lo que es back con Python estamos los dos en bolas iría por Node.
Javascript sabemos los dos y yo tengo algo de experiencia con Node y Express.

**Comment by marianoheller** [comment]
A la tarde rebaustizo el repo y reinicializo las carpetas con front/back asi queda masomenos armado.
Also, dos cosas:
1) Que nombre le pongo? jaja
2) Tema deadline, que disponibilidad tenés? Te parece apuntar a tenerlo listo para la proxima planning?

**Comment by ivanfranco502** [comment]
Dale, disponibilidad un par de horas a la semana jajaja
