### ISSUE TITLE
Escalas

### ISSUE THREAD

**Issue by marianoheller** [marianoheller/rageboard#22]
Crear un modulo q transforme medicion a un numero mostrable.
El dominio de cada escala va a depender de cada medicion mientras q la imagen es siempre de 0 a 100 (lo q muestra el gauge).

Por ejemplo, la escala de temperatura va a mapper numeros de 0 a 40 a numeros de 0 a 100.

**Comment by ivanfranco502** [comment]
En ML cuando se necesita comparar distintas medidas, lo que se hace es
normalización. Básicamente llevar todo al mismo idioma. Eso es una fórmula
simil promedio.

**Comment by marianoheller** [comment]
Pasa depende de cada medicion no? De el idioma de cada medicion.
Osea, ponele la temperatura, yo me imagino q
* Si hace 40°C ponele da 100% de enojo
* y si hay 20°C da 0%
* Peero cuando hay 0°C tambien daria 100% xq mucho frio es "malo".

Entonces en este caso la funcion mappeo si la graficaramos seria como una U.

Y como ejemplo contrario a la temperatura : El dolar.
* Si sube, sube el enojo
* si baja, baja el enojo 

Por lo que abria una relacion lineal/exponencial/lo q sea pero siempre creciente.

**Comment by marianoheller** [comment]
Hay una libreria para graficar (q creo q te la habia nombrado) q hace basicamente eso cuando definis las graficos. Creas "escalas" y le definis el dominio, la imagen, interpolador custom, etc.
Y eso te devuelve una funcion q aplicas a cada x para obtener tu y.
https://github.com/d3/d3-scale

**Comment by marianoheller** [comment]
Bueno, ayer me puse un rato con esto y si bien lo q incumbe al issue estaria hecho me di cuenta de algo.
No podemos pedir data a las api's cada vez q haya un request, dado q si se conectan N clientes vamos a estar pidiendo N veces la misma data.
Y encima cada servicio tiene una limitacion de reqs/dia distinta.

Veo dos soluciones:
1) La más simple, cachear la respuesta y solo renovar la medicion cuando el timestamp sea suficientemente viejo (tendria q ser el denominador común de las reqs/dia)
2) Persistir en una nosql simple cada data con su timestamp o ttl y tener una especia de rutina batch q vaya actualizando cuando sea necesario cada una. En este caso el backend siempre leeria de la db las mediciones y las juntaria en un unico valor.

La opcion tampoco es super compleja, simplemente es un poco más de trabajo.
